const chapters = [
  {label:'CHAPTER 01', name:'THE BEGINNING', cls:'birth', html:`<div class="scene center"><p class="eyebrow">a little birthday journey</p><p class="tiny-heart">♡</p><h1>It all began<br><em>with you.</em></h1><p class="sub">Before I ever knew your name, Before the CA dream, before everything, The all that mattered is : Your birth and your very first presence itself.</p><div class="birth-card"><span>THE BEST CHAPTER OF YOUR LIFE</span><strong>CHAPTER 1</strong><small>the day you were born</small></div><button class="glow-btn" data-next>Begin with short recall <span>♡</span></button></div>`},
  {label:'CHAPTER 02', name:'THE First text', cls:'origin', html:`<div class="scene center"><p class="eyebrow">chapter 02 · first message</p><h2>The girl who<br><em>asked for help.</em></h2><div class="chat"><div class="bubble n">Nandu: Bibek Can you help me with this?</div><div class="bubble me">Me: Yeah,why not. Here it is. .</div><div class="bubble n">Nandu: okayy, Thanks :)</div><div class="typing">and somehow... after then the conversation kept going <span>♡</span></div></div><button class="glow-btn" data-next>open chapter 03 →</button></div>`},
  {label:'CHAPTER 03', name:'FIRST MEETUP', cls:'meet', html:`<div class="scene center"><p class="eyebrow">chapter 03 · first meetup</p><h2>The first<br><em>meetup.</em></h2><div class="single-photo"><img src="assets/images/first-meetup.jpg" alt="First meetup"><span>No photo of ours but this was my look that day ♡</span></div><button class="glow-btn" data-next>keep the story going →</button></div>`},
  {label:'CHAPTER 04', name:'LATE NIGHT', cls:'late', html:`<div class="scene center"><p class="eyebrow">chapter 04 · 02:47 AM</p><div class="moon"></div><div class="time">02:47:19</div><h2>The late-night<br><em>department.</em></h2><p class="sub">Some conversations had absolutely no business lasting that long but dit even till 4 am one day.</p><div class="floating-hearts">♡　♡　♡</div><button class="glow-btn" data-next>My best experiences with you ♡</button></div>`},
  {label:'CHAPTER 05', name:'Timro BLOCKING CHRONICLES', cls:'blocking', html:`<div class="scene center"><p class="eyebrow">chapter 05 · classified</p><div class="block-stamp">YOU HAVE BEEN BLOCKED</div><h2>The Blocking<br><em>Chronicles.</em></h2><p class="sub">A remarkably consistent tradition. Most the repeated thing you have done to me. Blocking and unblocking on every platform possible, may be 1000 times. Still today I'm blocked 😭</p><button class="glow-btn danger-btn block-main" id="blockBtn">Still wiling to block me? Press it. </button><div id="blockMsg" class="interaction-msg">Press it. You know you want to.</div><div class="block-count">incidents recorded: <strong id="blockCount">0</strong></div><button class="glow-btn small" data-next>escape this chapter →</button></div>`},
  {label:'CHAPTER 06', name:'Your LAUGH', cls:'laugh', html:`<div class="scene center"><p class="eyebrow">chapter 06 · auditory warning</p><div class="warning-orb">!</div><h2>That scary cum<br><em>mesmerizing laugh.</em></h2><p class="sub">Warning: once released, there may be no going back.</p><div class="wave" id="laughWave"></div><button class="glow-btn" id="laughBtn">accept the risk and play the laugh ♡</button><p id="laughMsg" class="interaction-msg"></p><button class="glow-btn small save-me-btn" id="saveMeBtn" style="display:none">Save me ⚠</button></div>`},
  {label:'CHAPTER 07', name:'MY VOICE NOTE', cls:'voice-note', html:`<div class="scene center"><p class="eyebrow">chapter 07 · one from me</p><div class="voice-orb">🎙</div><h2>My <em>voice note.</em></h2><p class="sub">A little something I wanted you to hear rather than read.</p><div class="wave" id="voiceWave"></div><button class="glow-btn" id="voiceBtn">Tell me what you what to say</button><p id="voiceNoteMsg" class="hand">Your voice note will play here.</p><button class="glow-btn small" id="voiceMoreBtn" style="display:none">Show more →</button></div>`},
  {label:'CHAPTER 08', name:'THE ANGER', cls:'anger', html:`<div class="scene center"><p class="eyebrow">chapter 08 · threat assessment</p><div class="rage-face">◉</div><h2>How much angry<br><em>are you today?</em></h2><input id="rageInput" class="rage-input" type="range" min="0" max="100" value="20" aria-label="Nandu anger meter"><div class="rage-track"><span id="rage"></span></div><p id="rageText" class="hand">seems safe... for now.</p><button class="glow-btn" data-next>leave before it escalates →</button></div>`},
  {label:'CHAPTER 09', name:'THE PEOPLE YOU LOVE', cls:'family', html:`<div class="scene center"><p class="eyebrow">chapter 09 · the people</p><h2>The people<br><em>you love.</em></h2><div class="love-cards photo-family-cards"><article><span>♡</span><b>Parents</b><div class="family-photo-placeholder"><img src="assets/images/parents.jpg" alt="Unnati with her parents"></div><p>The people who mean home to you.</p></article><article><span>♡</span><b>Sister</b><div class="family-photo-placeholder"><img src="assets/images/sister.jpg" alt="Unnati with her sister"></div><p>One of your biggest loves.</p></article></div><p class="hand">Some things say a lot about a person. I notice this quality the most.</p><button class="glow-btn" data-next>open chapter 10 →</button></div>`},
  {label:'CHAPTER 10', name:'THE CA DREAM', cls:'ca', html:`<div class="scene center"><p class="eyebrow">chapter 10 · the dream</p><div class="ca-name">UNNATI DHAKAL</div><div class="ca-badge">CA</div><div class="signature">Unnati Dhakal, CA</div><p class="sub">I've seen how badly you want it. So keep going until that signature is real.</p><button class="glow-btn light-btn" data-next>next chapter →</button></div>`},
  {label:'CHAPTER 11', name:'CHILDHOOD', cls:'childhood', html:`<div class="scene center"><p class="eyebrow">chapter 11 · before everything</p><h2>Once upon a<br><em>tiny Nandu.</em></h2><div class="childhood-photos"><div class="child-photo"><img src="assets/images/childhood-01.jpg" alt="Childhood photo 1"><span>The clusmy yet asthetic nanu ♡</span></div><div class="child-photo second"><img src="assets/images/childhood-02.jpg" alt="Childhood photo 2"><span>Killer version, Baddie banney lakshyan ♡</span></div></div><p class="hand">A little person, long before all the chapters that came after.</p><button class="glow-btn" data-next>Want to see something ?</button></div>`},
  {label:'CHAPTER 12', name:'THE PHOTO ROOM', cls:'photo-room', html:`<div class="scene"><div class="chapter-head center"><p class="eyebrow">chapter 12 · enter the room</p><h2>Some of my favorites<br><em>of yours that i have.</em></h2><p>Click, tap, flip, zoom — and leave room for two TikTok videos too.</p></div><div class="photo-stage" id="photoStage"></div><div class="tiktok-spots"><div class="tiktok-slot"><video src="assets/tiktoks/tiktok-01.mp4" controls playsinline preload="metadata"></video></div><div class="tiktok-slot"><video src="assets/tiktoks/tiktok-02.mp4" controls playsinline preload="metadata"></video></div></div><div class="center"><button class="glow-btn" data-next>leave the room →</button></div></div>`},
  {label:'CHAPTER 13', name:'THINGS I NOTICE', cls:'notice', html:`<div class="scene center"><p class="eyebrow">chapter 13 · observed</p><h2>Things I<br><em>notice.</em></h2><p class="surprise-hint">Four little secrets are waiting behind the glowing seals.</p><div class="notice-grid surprise-grid"><article data-surprise="The CA obsession.\nNot just a title. A destination."><div class="surprise-cover"><span class="seal">♡</span><b>There is more here</b><small>touch the seal ✦</small><i>✧</i></div></article><article data-surprise="The family.\nYou love your people with your whole heart."><div class="surprise-cover"><span class="seal">♡</span><b>A little secret</b><small>open when curious</small><i>✧</i></div></article><article data-surprise="The chaos.\nThe singing. The anger. That laugh. The constant blocking."><div class="surprise-cover"><span class="seal">♡</span><b>Do not peek?</b><small>you probably should ✦</small><i>✧</i></div></article><article data-surprise="The effort you put for someone that matters to you.\nSome things are remembered because they mattered."><div class="surprise-cover"><span class="seal">♡</span><b>One more thing</b><small>break the seal</small><i>✧</i></div></article></div><p class="hand">Tap any glowing cover and let it surprise you. ♡</p><button class="glow-btn" data-next>keep going →</button><div class="surprise-modal" id="surpriseModal"><div class="surprise-modal-card"><button class="modal-close" id="surpriseClose">×</button><p class="eyebrow">a little surprise ♡</p><p id="surpriseText"></p></div></div></div>`},
  {label:'CHAPTER 14', name:'THE FIRST TRY I MADE', cls:'bouquet', html:`<div class="scene center"><p class="eyebrow">chapter 14 · one memory</p><div class="bouquet-frame small-bouquet"><img src="assets/images/bouquet.jpg" alt="Bouquet memory"><span>the first effort · Don't know why but still ♡</span></div><h2>Some memories<br>hit <em>differently.</em></h2><div class="effort-wheel-wrap"><button class="effort-wheel" id="effortWheel" aria-label="Spin some efforts memory"><span>Spin some efforts memory</span><b>✦</b></button><div class="wheel-pointer">♥</div></div><p class="spin-count" id="spinCount">SPINS 0 / 5</p><p class="sub" id="effortResult">Spin it. Let one old effort return for a second. ♡</p><button class="glow-btn" data-next>turn the page →</button><div class="effort-modal" id="effortModal"><div class="effort-modal-card"><span>✦ A MEMORY OF EFFORT ✦</span><p id="effortPopupText"></p></div></div></div>`},
  {label:'CHAPTER 15', name:'THE COMPLICATED BIT', cls:'complicated', html:`<div class="scene center"><p class="eyebrow">chapter 15 · the honest page</p><h2>Not everything<br>went <em>right.</em></h2><div class="fragments"><span>wrong turns</span><span>misunderstandings</span><span>distance</span><span>things left unsaid</span></div><p class="sub">No need to rewrite the past. It happened. It became part of the story.</p><button class="glow-btn" data-next>turn the page →</button></div>`},
  {label:'CHAPTER 16', name:'THE ALMOST CHAPTER', cls:'almost', html:`<div class="scene center"><p class="eyebrow">chapter 16 · the almost chapter</p><div class="heart-outline">♡</div><h2>Some chapters<br>never got <em>written.</em></h2><p class="sub">Maybe some stories are allowed to remain unfinished and still be meaningful.</p><button class="glow-btn" data-next>open chapter 17 →</button></div>`},
  {label:'CHAPTER 17', name:'THE WRONG ENTRY', cls:'ex', html:`<div class="scene center"><p class="eyebrow">chapter 17 · system correction</p><div class="wrong-entry">WRONG PERSON ENTERED<br><small>the ex was an incorrect entry — respectfully.</small></div><h2>Plot twist.<br><em>Wrong chapter.</em></h2><p class="sub">No disrespect to anyone. But in the story of your life, that entry simply belonged to another page — and the page is now turned.</p><button class="glow-btn" data-next>correct the entry →</button></div>`},
  {label:'CHAPTER 18', name:'I MET YOU IN FOUNDATION', cls:'met', html:`<div class="scene center"><p class="eyebrow">chapter 18 · and then</p><div class="meeting-light"></div><h2>I <em>met</em> you.</h2><p class="sub">And somewhere between the study questions, late nights, ridiculous moments and everything that happened after... it became a part of the foundation journey.</p><div class="heart-line">♡────────♡</div><button class="glow-btn" data-next>one last chapter before 20 →</button></div>`},
  {label:'CHAPTER 19', name:'LAST NIGHT OF 19', cls:'midnight', html:`<div class="scene center"><p class="eyebrow">chapter 19 · the final night of 19</p><div class="clock" id="clock">20</div><div class="countdown-clock" id="countdownClock"><div class="clock-face"><span class="clock-hand" id="clockHand"></span><span class="clock-center">♡</span>${Array.from({length:20},(_,i)=>`<span class="clock-number n${i+1}" data-note="${i+1}">${i+1}</span>`).join('')}</div></div><div class="chapter-note" id="chapterNote">Ready for the last night of 19? ♡</div><div class="clock-memory-popup" id="clockMemoryPopup"><span>✦ CHAPTER MEMORY ✦</span><strong id="clockMemoryText"></strong></div><button class="glow-btn" id="midnightBtn">start the countdown ✦</button></div>`},
  {label:'CHAPTER 20', name:'NEW JOURNEY', cls:'candle', html:`<div class="scene center candle-scene"><div class="candle-banners">HAPPY BIRTHDAY ♡　20 ♡　HAPPY BIRTHDAY</div><p class="eyebrow">chapter 20 · goodbye teenage years</p><div class="celebration-top">20 YEARS <span>♡</span></div><h2>Goodbye to teen age years.<br><em>Welcome to your twenties.</em></h2><p class="sub">Welcome to your twenties and best wishes for new journey.</p><div class="birthday-decor">✦　🎈　♡　🎉　♡　🎈　✦</div><div class="candle-balloons" aria-hidden="true">🎈　🎈　　　　　　　　　🎈　🎈</div><button class="glow-btn" id="lightBtn">Make a wish and blow the candle</button><div class="cake-wrap"><div class="cake"><div class="cake-plate"></div><div class="cake-top"><span class="cake-glaze"></span></div><div class="cake-body"><span class="cake-layer layer-one"></span><span class="cake-layer layer-two"></span><span class="cake-drip drip-one"></span><span class="cake-drip drip-two"></span></div><div class="cake-cream cream-one"></div><div class="cake-cream cream-two"></div><div class="icing">♡　♡　♡</div><div class="cake-decoration">✦　♡　✦</div></div><div class="candles" id="candles"></div><button class="cake-knife" id="cakeKnife" style="display:none" aria-label="Cut the birthday cake">🔪<span>Cut the cake</span></button></div><div class="blow" id="blowUI">Blow gently — the flames are listening. <button class="glow-btn small" id="blowBtn">tap / swipe if microphone is unavailable</button></div><div class="celebrate-note" id="celebrateNote">Make a wish, Nandu. ♡</div></div>`},
  {label:'CHAPTER 20 · CELEBRATION', name:'THE CELEBRATION', cls:'celebrate', html:`<div class="scene center"><div class="confetti" id="confetti"></div><div class="balloon b1">♡</div><div class="balloon b2">♡</div><div class="balloon b3">♡</div><p class="eyebrow">the candles are gone · the celebration begins</p><h2>HAPPY 20TH,<br><em>NANDU!</em></h2><p class="sub">The teenage chapter is officially closed.<br>Now go make your twenties ridiculously beautiful.</p><div class="party-line">🎂　♡　✦　🎈　♡　✦　🎂</div><button class="glow-btn" data-next>What's next →</button></div>`},
  {label:'CHAPTER 20 · YOUR SONG', name:'YOUR  SINGING', cls:'song', html:`<div class="scene center"><p class="eyebrow">a little late-night birthday concert</p><div class="spotlight"></div><h2>For <em>you.</em></h2><p class="sub">A tiny birthday stage, even if the original audio disappeared.</p><div class="record-player big"><div class="record"></div><div class="needle"></div></div><button class="glow-btn" id="finalSongBtn">play the recording ♫</button><p id="finalSongNote" class="hand">Ready.</p><button class="glow-btn small" data-next>one last thing →</button></div>`},
  {label:'CHAPTER 20 · THE LETTER', name:'THE LITTLE LETTER', cls:'letter', html:`<div class="scene center"><div class="ancient-envelope" id="ancientEnvelope"><div class="envelope-ribbon"></div><div class="envelope-flap"></div><div class="envelope-seal">♡</div><div class="envelope-paper"><p class="eyebrow">one last thing · dear Nandu</p><div class="letter-text" id="letterText"></div><textarea class="letter-editor" id="letterEditor" aria-label="Edit your letter later"></textarea><p class="signoff">— from someone who apparently over-engineers birthday wishes ♡</p></div></div><button class="glow-btn light-btn" id="discloseLetter">Disclose the letter ♡</button><div class="letter-reading" id="letterReading"><button class="letter-close" id="letterClose">×</button><div class="letter-reading-paper"><p class="eyebrow">chapter 20 · a little letter</p><div class="letter-reading-text" id="letterReadingText"></div><textarea class="letter-reading-editor" id="letterReadingEditor" aria-label="Edit your final letter"></textarea><p class="signoff">— from someone who apparently over-engineers birthday wishes ♡</p></div></div><button class="glow-btn small" data-next>open the final chapter →</button></div>`},
  {label:'CHAPTER 01 · THE BEGINNING', name:'THE BEST CHAPTER OF YOUR LIFE', cls:'end', html:`<div class="scene center"><p class="eyebrow">the beginning was always the best secret</p><div class="baby-frame"><img src="assets/images/baby-photo.jpg" alt="Baby photo"></div><h2>The best chapter<br>was <em>chapter 1.</em></h2><p class="sub">Because every beautiful story needs a beginning. And yours began the day you were born.</p><p class="hand">Now go write the rest. Press The love button below ♡</p><button class="secret" id="secret">♡</button><p id="secretText" class="secret-text">Please unblock me and also don't block me for making this. 😭<br><span>You really are worth the unnecessary effort.</span></p></div>`}
];

const app=document.querySelector('#app'), dots=document.querySelector('#dots'), chapterNo=document.querySelector('#chapterNo'), chapterName=document.querySelector('#chapterName');
let current=0, audio=null, laughAudio=null, voiceAudio=null, happyBirthdayAudio=null, singingAudio=null, startedCandle=false, blown=0, countdownRunning=false;

chapters.forEach((c,i)=>{const s=document.createElement('section');s.className='chapter '+(c.cls||'');s.innerHTML=c.html;s.dataset.i=i;app.appendChild(s);const d=document.createElement('button');d.className='dot';d.title=`${c.label}: ${c.name}`;d.onclick=()=>go(i);dots.appendChild(d)});
const els=[...document.querySelectorAll('.chapter')], ds=[...document.querySelectorAll('.dot')];
function updateBanner(){const c=chapters[current];chapterNo.textContent=c.label;chapterName.textContent=c.name;}
function fitScene(chapter){const scene=chapter?.querySelector('.scene');if(!scene)return;scene.style.setProperty('--scene-scale','1');requestAnimationFrame(()=>{const style=getComputedStyle(chapter),availableH=chapter.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom)-8,availableW=chapter.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)-8;const naturalH=scene.scrollHeight,naturalW=scene.scrollWidth;let scale=Math.min(1,availableH/Math.max(naturalH,1),availableW/Math.max(naturalW,1));if(scale<.46)scale=.46;scene.style.setProperty('--scene-scale',scale.toFixed(3));});}
function go(n){if(n<0||n>=els.length||n===current)return;els[current].classList.remove('active');els[current].classList.add('exit');setTimeout(()=>els[current]?.classList.remove('exit'),850);current=n;els[current].classList.add('active');updateBanner();ds.forEach((d,i)=>d.classList.toggle('active',i===n));pulseHearts();fitScene(els[current]);if(n===21)launchConfetti();}
els[0].classList.add('active');ds[0].classList.add('active');updateBanner();fitScene(els[0]);
window.addEventListener('resize',()=>fitScene(els[current]));window.addEventListener('load',()=>fitScene(els[current]));document.fonts?.ready?.then(()=>fitScene(els[current]));

document.addEventListener('click',e=>{const b=e.target.closest('[data-next]');if(b)go(current+1)});
document.querySelector('#prevBtn').onclick=()=>go(current-1);document.querySelector('#nextBtn').onclick=()=>go(current+1);

function pulseHearts(){const holder=document.querySelector('#hearts');if(!holder)return;holder.innerHTML='';for(let i=0;i<18;i++){const h=document.createElement('span');h.textContent=Math.random()>.3?'♡':'♥';h.style.left=Math.random()*100+'%';h.style.top=(10+Math.random()*78)+'%';h.style.animationDelay=Math.random()*1.8+'s';h.style.fontSize=(12+Math.random()*24)+'px';holder.appendChild(h)}}pulseHearts();

// Welcome overlay
const welcomeOverlay=document.querySelector('#welcomeOverlay'), letMeSee=document.querySelector('#letMeSeeBtn'), noThanks=document.querySelector('#noThanksBtn');
function moveNoThanks(){if(!noThanks)return;const area=welcomeOverlay.querySelector('.welcome-actions');const r=area.getBoundingClientRect();const b=noThanks.getBoundingClientRect();noThanks.style.position='absolute';const safeX=Math.max(8,r.width-b.width-8),safeY=Math.max(8,Math.min(r.height-b.height-8,r.height*.42));noThanks.style.left=(8+Math.random()*safeX)+'px';noThanks.style.top=(8+Math.random()*safeY)+'px';noThanks.style.zIndex='4';}
['mouseenter','pointerdown','touchstart','mousedown','focus','click'].forEach(ev=>noThanks?.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();moveNoThanks()}));
letMeSee?.addEventListener('click',()=>{welcomeOverlay.classList.add('closing');celebrationBurst(welcomeOverlay);setTimeout(()=>welcomeOverlay.classList.add('hidden'),1500)});
function celebrationBurst(scope){const box=document.createElement('div');box.className='welcome-celebration';box.innerHTML='♡　✦　♥　✧　♡　✦　♥';scope.appendChild(box);setTimeout(()=>box.remove(),1400)}

// Chapter 05: escalating blocking joke
const block=document.querySelector('#blockBtn');
if(block)block.addEventListener('click',()=>{const msg=document.querySelector('#blockMsg'),count=document.querySelector('#blockCount');const n=(+msg.dataset.n||0)+1;msg.dataset.n=n;const lines=[
  'I am still here. 😭',
  'I am still trying. 😢😢',
  'I am still surviving. 🥺😢😭',
  'I am still coming back. 😭😩🥺😢',
  'I am still here... somehow. 😭😭😭😩🥺💔',
  'I am done. 😭💔🥀'
];
msg.textContent=lines[Math.min(n-1,lines.length-1)];msg.classList.toggle('huge',n>=4);msg.style.fontSize=`${22+n*9}px`;count.textContent=n;block.style.transform=`scale(${Math.max(.08,1-n*.15)})`;if(n>=6){block.style.pointerEvents='none';block.style.opacity='0';setTimeout(()=>block.remove(),300)}else{block.animate([{transform:`scale(${Math.max(.08,1-n*.15)}) translateX(0)`},{transform:`scale(${Math.max(.08,1-n*.15)}) translateX(-12px)`},{transform:`scale(${Math.max(.08,1-n*.15)}) translateX(12px)`},{transform:`scale(${Math.max(.08,1-n*.15)}) translateX(0)`}],{duration:360})}});

// Chapter 06 laugh audio
const laugh=document.querySelector('#laughBtn');
if(laugh)laugh.onclick=()=>{document.querySelector('#laughMsg').textContent='⚠ RISK RELEASED. Please remain calm. 😭';animateWave('#laughWave');if(CONFIG.songs.laugh){laughAudio=new Audio(CONFIG.songs.laugh);laughAudio.play().catch(()=>{document.querySelector('#laughMsg').textContent='⚠ Add your laugh recording, then press again.'});}laugh.style.display='none';document.querySelector('#saveMeBtn').style.display='inline-flex'};
document.querySelector('#saveMeBtn')?.addEventListener('click',()=>{document.querySelector('.laugh')?.classList.add('relief');setTimeout(()=>go(6),700)});

// Chapter 07 voice note
const voiceBtn=document.querySelector('#voiceBtn'),voiceMore=document.querySelector('#voiceMoreBtn');
voiceBtn?.addEventListener('click',()=>{if(CONFIG.songs.voiceNote){voiceAudio=new Audio(CONFIG.songs.voiceNote);voiceAudio.play().catch(()=>{document.querySelector('#voiceNoteMsg').textContent='Add your voice note recording, then press again.'});document.querySelector('#voiceNoteMsg').textContent='Playing your voice note ♫';}else{document.querySelector('#voiceNoteMsg').textContent='Add your voice note file to activate this.'}voiceBtn.style.display='none';voiceMore.style.display='inline-flex';animateWave('#voiceWave')});
voiceMore?.addEventListener('click',()=>go(7));

// Chapter 08 anger meter (from the V3 anger chapter)
const rageInput=document.querySelector('#rageInput'),rageFill=document.querySelector('#rage'),rageText=document.querySelector('#rageText');
function updateRage(){if(!rageInput||!rageFill||!rageText)return;const v=+rageInput.value;rageFill.style.width=v+'%';rageText.textContent=v<25?'seems safe... for now.':v<50?'okay... slightly dangerous.':v<75?'warning: proceed carefully.':'RUN. SHE IS ANGRY. 😭';}
rageInput?.addEventListener('input',updateRage);updateRage();

function makeWave(id){const w=document.querySelector(id);if(!w)return;for(let i=0;i<48;i++){const x=document.createElement('i');x.style.setProperty('--h',12+Math.random()*65+'px');x.style.animationDelay=Math.random()*.8+'s';w.appendChild(x)}}
function animateWave(id){document.querySelector(id)?.classList.add('active');setTimeout(()=>document.querySelector(id)?.classList.remove('active'),2200)}makeWave('#laughWave');makeWave('#voiceWave');makeWave('#singWave');

function playAudio(path,noteId){if(!path)return false;const a=new Audio(path);a.loop=false;a.play().catch(()=>{});if(noteId)document.querySelector(noteId).textContent='Playing ♫';return a}
const sing=document.querySelector('#singBtn');if(sing)sing.onclick=()=>{if(!CONFIG.songs.singing){document.querySelector('#singNote').textContent='Add the singing recording first.';return}if(singingAudio?.paused===false){singingAudio.pause();sing.textContent='play her song ♫';return}singingAudio=playAudio(CONFIG.songs.singing,'#singNote');sing.textContent='pause ♫'};

// Chapter 09 photo placeholders are already in the HTML. Chapter 12 photo room.
const stage=document.querySelector('#photoStage');if(stage){CONFIG.memories.slice(0,8).forEach((m,i)=>{const p=document.createElement('div');p.className='polaroid p'+(i+1);p.innerHTML=m.image?`<img src="${m.image}" alt="${m.title}"><span>${m.caption}</span>`:`<div class="photo-placeholder">PHOTO ${i+1}</div><span>${m.caption}</span>`;p.addEventListener('click',()=>p.classList.toggle('focus'));stage.appendChild(p)})}

// Chapter 13 surprise boxes
const surpriseModal=document.querySelector('#surpriseModal'), surpriseText=document.querySelector('#surpriseText');
document.querySelectorAll('.surprise-grid article').forEach(card=>card.addEventListener('click',()=>{surpriseText.textContent=card.dataset.surprise;surpriseModal.classList.add('show')}));
document.querySelector('#surpriseClose')?.addEventListener('click',()=>surpriseModal.classList.remove('show'));

// Chapter 14 effort wheel — five spins, one three-second memory popup each time.
const effortWheel=document.querySelector('#effortWheel'),effortPopup=document.querySelector('#effortModal'),effortPopupText=document.querySelector('#effortPopupText'),spinCount=document.querySelector('#spinCount');
const effortLines=[
 'That printed letter, first to any girl.',
 'That missing poster which i made just to convince you',
 'The very long new year wish',
 'Rain of calls and messages after blockage from every where',
 'Chocolate (though not expensive) but from my own earned money',
 'Website and those irritating letters full of CA language',
 'Many more subtle and small, though still less'
];
let effortRotation=0,effortSpins=0,effortBusy=false;
function showEffortPopup(line){if(!effortPopup||!effortPopupText)return;effortPopupText.textContent=line;effortPopup.classList.add('show');setTimeout(()=>effortPopup.classList.remove('show'),3000);}
effortWheel?.addEventListener('click',()=>{if(effortBusy||effortSpins>=5)return;effortBusy=true;effortSpins++;effortRotation+=1440+Math.floor(Math.random()*4)*360+Math.floor(Math.random()*360);effortWheel.style.transform=`rotate(${effortRotation}deg)`;if(spinCount)spinCount.textContent=`SPINS ${effortSpins} / 5`;setTimeout(()=>{const line=effortLines[Math.floor(Math.random()*effortLines.length)];document.querySelector('#effortResult').textContent='✦ '+line+' ✦';showEffortPopup(line);celebrationBurst(document.querySelector('.bouquet'));effortBusy=false;if(effortSpins>=5){setTimeout(()=>go(14),3100)}},1800)});

// Chapter 19 — 20 visual countdown numbers, each chapter memory held for 4 seconds.
const chapterNotes=[
 'your scary laugh','your determination','the first message','that first meetup','late-night calls','your anger','your singing','the blocking tradition','your family love','the CA dream','your childhood','my favorite photos','the things I notice','the first bouquet','the complicated bits','the almost chapter','the wrong entry','I met you','the last night of 19','your new twenties'
];
const noteEls=[...document.querySelectorAll('.clock-number')];
function positionClockNumbers(){noteEls.forEach((el,i)=>{const a=(i/20)*Math.PI*2-Math.PI/2;const r=42;el.style.left=`calc(50% + ${Math.cos(a)*r}%)`;el.style.top=`calc(50% + ${Math.sin(a)*r}%)`;el.style.transform='translate(-50%,-50%)';el.textContent=i+1})}positionClockNumbers();
const midnight=document.querySelector('#midnightBtn');
midnight?.addEventListener('click',()=>{if(countdownRunning)return;countdownRunning=true;midnight.disabled=true;let visual=20,idx=0;const clock=document.querySelector('#clock'),note=document.querySelector('#chapterNote'),hand=document.querySelector('#clockHand'),popup=document.querySelector('#clockMemoryPopup'),popupText=document.querySelector('#clockMemoryText');function tick(){if(idx>=20){clock.textContent='♡';note.textContent='20 candles are waiting. ♡';if(popup)popup.classList.remove('show');setTimeout(()=>go(20),1200);return}clock.textContent=String(visual);note.textContent=chapterNotes[idx];noteEls.forEach((el,i)=>el.classList.toggle('current',i===idx));if(hand)hand.style.transform=`translate(-50%,-100%) rotate(${idx*18}deg)`;if(popup&&popupText){popupText.textContent=chapterNotes[idx];popup.classList.remove('show');void popup.offsetWidth;popup.classList.add('show');setTimeout(()=>popup.classList.remove('show'),3600)}idx++;visual--;setTimeout(tick,4000)}tick()});

// Chapter 20 candles + birthday song + microphone/tap/swipe + cake cutting.
const candleRow=document.querySelector('#candles');if(candleRow){for(let i=0;i<20;i++){const c=document.createElement('div');c.className='candle-stick';c.innerHTML='<span class="flame"></span><small>'+ (i+1) +'</small>';candleRow.appendChild(c)}}
const candleEls=[...document.querySelectorAll('.candle-stick')],lightBtn=document.querySelector('#lightBtn'),blowUI=document.querySelector('#blowUI'),cakeKnife=document.querySelector('#cakeKnife');
function celebrateProgress(){const note=document.querySelector('#celebrateNote');note.textContent=blown<7?'The first ones are flickering... ♡':blown<14?'Keep going, birthday girl ✦':blown<20?'Almost there... one last breath. ♡':'TWENTY! The cake is waiting. 🎂'}
function extinguish(n=1){if(!startedCandle)return;for(let i=0;i<n&&blown<20;i++){candleEls[blown].classList.add('off');blown++}celebrateProgress();if(blown>=20){if(happyBirthdayAudio){happyBirthdayAudio.pause();happyBirthdayAudio.currentTime=0}blowUI.innerHTML='<strong>All twenty are out! ✦ Now cut your birthday cake. 🎂</strong>';if(cakeKnife)cakeKnife.style.display='flex';launchConfetti();const clap=document.createElement('div');clap.className='clap-burst';clap.textContent='👏　👏　👏　🎉　👏　👏';document.querySelector('.candle')?.appendChild(clap)}}
lightBtn?.addEventListener('click',async()=>{startedCandle=true;lightBtn.style.display='none';blowUI.style.display='block';if(CONFIG.songs.happyBirthday){happyBirthdayAudio=new Audio(CONFIG.songs.happyBirthday);happyBirthdayAudio.loop=true;happyBirthdayAudio.play().catch(()=>{document.querySelector('#celebrateNote').textContent='Tap again after adding your birthday recording. ♡'})}try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('no microphone');const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ac=new AudioContext(),an=ac.createAnalyser();an.fftSize=256;ac.createMediaStreamSource(stream).connect(an);const data=new Uint8Array(an.frequencyBinCount);const loop=()=>{if(!startedCandle||blown>=20){stream.getTracks().forEach(t=>t.stop());return}an.getByteTimeDomainData(data);let s=0;for(const v of data){const q=(v-128)/128;s+=q*q}if(Math.sqrt(s/data.length)>.11)extinguish(Math.max(1,Math.ceil(Math.random()*2)));requestAnimationFrame(loop)};loop()}catch(e){document.querySelector('#celebrateNote').textContent='Microphone unavailable — tap or swipe across the candle area. ♡'}});
document.querySelector('#blowBtn')?.addEventListener('click',()=>extinguish(2));
let candleSwipeX=0,candleSwipeY=0,candlePointerDown=false;const candleArea=document.querySelector('.candle-scene');candleArea?.addEventListener('pointerdown',e=>{if(!startedCandle||blown>=20)return;candlePointerDown=true;candleSwipeX=e.clientX;candleSwipeY=e.clientY});candleArea?.addEventListener('pointerup',e=>{if(!candlePointerDown)return;candlePointerDown=false;const dx=e.clientX-candleSwipeX,dy=e.clientY-candleSwipeY;if(Math.hypot(dx,dy)>35){e.stopPropagation();extinguish(2)}});
cakeKnife?.addEventListener('click',()=>{cakeKnife.classList.add('cutting');document.querySelector('.cake')?.classList.add('cut');document.querySelector('#celebrateNote').textContent='Cake cut! Happy 20th, Nandu! 🎂♡';launchConfetti();setTimeout(()=>go(21),1500)});

function launchConfetti(){const conf=document.querySelector('#confetti');if(!conf)return;conf.innerHTML='';for(let i=0;i<150;i++){const x=document.createElement('i');x.textContent=['✦','♡','♥','✧','🎉','🎊'][i%6];x.style.left=Math.random()*100+'%';x.style.top=(-Math.random()*120)+'px';x.style.animationDelay=Math.random()*2.2+'s';x.style.fontSize=(12+Math.random()*18)+'px';conf.appendChild(x)}}

// Chapter 20 birthday-song continuation: exact requested message
const finalSong=document.querySelector('#finalSongBtn');if(finalSong)finalSong.onclick=()=>{document.querySelector('#finalSongNote').textContent='Sorry, no audio available as you deleted the ones you sent. So sing a song for yourself if free ♡';finalSong.disabled=true;};

// Ancient envelope letter — ribbon opens, then the letter rises into a full-screen reading view.
const disclose=document.querySelector('#discloseLetter'),ancientEnvelope=document.querySelector('#ancientEnvelope'),letterReading=document.querySelector('#letterReading'),letterClose=document.querySelector('#letterClose');
const letterText=document.querySelector('#letterText'),editor=document.querySelector('#letterEditor'),readingText=document.querySelector('#letterReadingText'),readingEditor=document.querySelector('#letterReadingEditor');
function syncLetter(value){if(letterText)letterText.textContent=value;if(readingText)readingText.textContent=value;if(editor&&editor.value!==value)editor.value=value;if(readingEditor&&readingEditor.value!==value)readingEditor.value=value}
syncLetter(CONFIG.finalMessage);
function openLetterReading(){if(!ancientEnvelope||!letterReading)return;ancientEnvelope.classList.add('open');setTimeout(()=>{letterReading.classList.add('show');syncLetter(editor?.value||CONFIG.finalMessage)},850);}
disclose?.addEventListener('click',()=>{openLetterReading();disclose.textContent='Letter disclosed ♡'});
letterClose?.addEventListener('click',()=>letterReading?.classList.remove('show'));
editor?.addEventListener('input',()=>syncLetter(editor.value));readingEditor?.addEventListener('input',()=>syncLetter(readingEditor.value));

const secret=document.querySelector('#secret');if(secret)secret.onclick=()=>document.querySelector('#secretText').classList.toggle('show');

document.querySelector('#musicBtn').onclick=()=>{if(!CONFIG.songs.background){document.querySelector('#musicBtn span').textContent='add audio';return}if(audio?.paused===false){audio.pause();document.querySelector('#musicBtn span').textContent='sound';return}audio=new Audio(CONFIG.songs.background);audio.loop=true;audio.play().catch(()=>{});document.querySelector('#musicBtn span').textContent='playing'};

window.addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(current+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}});
let wheelLock=false;window.addEventListener('wheel',e=>{if(wheelLock)return;wheelLock=true;go(current+(e.deltaY>0?1:-1));setTimeout(()=>wheelLock=false,850)},{passive:true});
let touchX=0;window.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});window.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>55)go(current+(dx<0?1:-1))},{passive:true});
